mode: learning
media_root: media/bootflat
media_url: /media/bootflat
title: kuroneko
base_url: /
template: hyde.ext.templates.jinja.Jinja2Template
context:
    data:
        author:
            name: HAYASAKA
            url: "hayasaka.ryosuke"
        menu:
          - title: Home
            url: index.html
