mode: learning
media_root: ./media
media_url: ./media

meta: 
    title: kuronekopages

base_url: /
template: hyde.ext.templates.jinja.Jinja2Template

plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.blockdown.BlockdownPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.grouper.GrouperPlugin
    - hyde.ext.plugins.markings.MarkingsPlugin
    - hyde.ext.plugins.markings.ReferencePlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - hyde.ext.plugins.stylus.StylusPlugin

context:
    data:
        author:
            name: HAYASAKA
            url: "hayasaka.ryosuke"
        menu:
          - title: Home
            url: index.html
publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../hayasaka-ryosuke.github.io/deploy
        url: git@github.com:HAYASAKA-Ryosuke/hayasaka-ryosuke.github.io.git
